name: Compile Win ARM64 (Python 3.13)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'DrissionPage Version'
        required: true
        default: 'v4.1.0.17'

permissions:
  contents: write

jobs:
  build-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64' # We use x64 Python to drive the cross-compiler

      - name: Install Dependencies
        run: |
          pip install nuitka requests cssselect setuptools
          choco install upx -y

      - name: Download DrissionPage Source
        shell: pwsh
        run: |
          $V = "${{ github.event.inputs.version }}"
          $URL = "https://github.com/g1879/DrissionPage/archive/refs/tags/$V.zip"
          Invoke-WebRequest -Uri $URL -OutFile "src.zip"
          Expand-Archive "src.zip" -DestinationPath "."
          $Extracted = Get-ChildItem -Directory -Filter "DrissionPage-*" | Select-
