name: Compile Win ARM64
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'DrissionPage Version'
        required: true
        default: 'v4.1.0.17'

jobs:
  build-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build ARM64
        run: |
          pip install nuitka requests cssselect
          choco install upx -y
          # Setup DrissionPage Source...
          $V = "${{ github.event.inputs.version }}"
          Invoke-WebRequest -Uri "https://github.com/g1879/DrissionPage/archive/refs/tags/$V.zip" -OutFile "src.zip"
          Expand-Archive "src.zip" -DestinationPath "."
          Move-Item "DrissionPage-*" "DrissionPage"
          
          # Nuitka Cross-Compile for ARM64
          python -m nuitka --module --lto=yes --follow-import-to=DrissionPage --output-dir=out_arm DrissionPage
          
          mkdir out_final
          $file = Get-ChildItem out_arm/*.pyd | Select-Object -First 1
          Copy-Item $file.FullName "out_final/drissionpage_win_arm64.pyd"
          Copy-Item $file.FullName "out_final/drissionpage_upx_win_arm64.pyd"
          upx --best --metadata=0 --strip-relocs=0 "out_final/drissionpage_upx_win_arm64.pyd"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: windows-arm64
          path: out_final/